ard = ">= 0.28.0"
name = "migr"

[dependencies]
decode = { git = "https://github.com/akonwi/ard-decode.git", commit = "917bf56" }
sql = { git = "https://github.com/akonwi/ard-sql.git", commit = "b622b65" }
