ard = ">= 0.28.0"
name = "migr"

[dependencies]
decode = { git = "https://github.com/akonwi/ard-decode.git", commit = "0b5b248" }
sql = { git = "https://github.com/akonwi/ard-sql.git", commit = "fcb7fa7" }
