use ard/testing

use migr/types

fn infer(database_url: Str) types::Dialect!Str {
  let trimmed = database_url.trim()
  
  try testing::assert(not trimmed.is_empty(), "Database URL cannot be empty")
  try testing::assert(not trimmed.contains("@tcp("), "MySQL is not supported in v1")
  try testing::assert(not trimmed.contains("@unix("), "MySQL is not supported in v1")
  
  Result::ok(types::Dialect::from(trimmed))
}
