
enum Command {
  init,
  create,
  up,
  down,
  status,
  validate,
  help,
}

fn Command::from(name: Str) Command? {
  match {
    name == "init" => Maybe::new(Command::init),
    name == "create" => Maybe::new(Command::create),
    name == "up" => Maybe::new(Command::up),
    name == "down" => Maybe::new(Command::down),
    name == "status" => Maybe::new(Command::status),
    name == "validate" => Maybe::new(Command::validate),
    name == "help" => Maybe::new(Command::help),
    _ => Maybe::new(),
  }
}

enum Dialect {
  postgres,
  sqlite,
}

impl Dialect {
  fn name() Str {
    match self {
      Dialect::postgres => "postgres",
      Dialect::sqlite => "sqlite",
    }
  }
}

enum Direction {
  up,
  down,
}

struct Config {
  program: Str,
  command: Command,
  migrations_dir: Str,
  database_url: Str?,
  create_name: Str?,
}

struct MigrationPart {
  number: Int,
  name: Str,
  direction: Direction,
  filename: Str,
}

struct Migration {
  number: Int,
  name: Str,
  up_path: Str,
  down_path: Str,
}
