use ard/maybe

enum Command {
  init,
  create,
  up,
  down,
  status,
  validate,
  help,
}

fn Command::from(name: Str) Command? {
  match {
    name == "init" => maybe::some(Command::init),
    name == "create" => maybe::some(Command::create),
    name == "up" => maybe::some(Command::up),
    name == "down" => maybe::some(Command::down),
    name == "status" => maybe::some(Command::status),
    name == "validate" => maybe::some(Command::validate),
    name == "help" => maybe::some(Command::help),
    _ => maybe::none(),
  }
}

enum Dialect {
  postgres,
  sqlite,
}

impl Dialect {
  fn name() Str {
    match self {
      Dialect::postgres => "postgres",
      Dialect::sqlite => "sqlite",
    }
  }
}

enum Direction {
  up,
  down,
}

struct Config {
  program: Str,
  command: Command,
  migrations_dir: Str,
  database_url: Str?,
  create_name: Str?,
}

struct MigrationPart {
  number: Int,
  name: Str,
  direction: Direction,
  filename: Str,
}

struct Migration {
  number: Int,
  name: Str,
  up_path: Str,
  down_path: Str,
}
